services:
  - type: web
    name: sales-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sales_dashboard_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
